### ISSUE TITLE
ilo sina li sona ala e nimi "kon"

### ISSUE THREAD

**Issue by increpare** [olpa/gf-tokipona#1]
mi toki e ni tawa ilo sina:

` parse "kon li pona ."`

ilo sina li toki e ni tawa mi:

`The parser failed at token 1: "kon"`

mi lukin e lipu pi ilo ni la, nimi "kon" li lon ala. ( https://github.com/olpa/gf-tokipona/blob/master/grammar/Tokipona.gf )

mi kama son a e ni tan seme?  mi pu e ilo sina.  ( https://gist.github.com/increpare/881d7f62a5f169014f09a6e9f110fe8a <- ni li toki ale tan lipu Sonja )

pona tawa sina, tawa pali sina :)

**Comment by olpa** [comment]
Pona! 
Lipu pi nimi mute tan URL ma seme? License li seme? Mi wile tawa ni: ilo mi jo nimi ni.

**Comment by increpare** [comment]
jan Olpa o, toki!

> Pona!
> Lipu pi nimi mute tan URL ma seme? License li seme? Mi wile tawa ni: ilo mi jo nimi ni.

a, tenpo pini la mi toki ike.  mi toki e ni: "ni li toki al**a** tan lipu Sonja".  taso mi wile toki e ni: "ni li toki al**e** tan lipu Sonja".  a a a 😅 

jan Sonja li toki e ni lon lipu ona:

> Lesson 1 to Lesson 3 and Part 3: Dictionaries are licensed under the Creative Commons Attribution-NonCommercial 4.0 International Licence: [http://creativecommons.org/licenses/by-nc/4.0/](http://creativecommons.org/licenses/by-nc/4.0/)
>
> Sample template you can use: 
>> This creative work by [your name] is based on the official Toki Pona book and website: http://tokipona.org 
> 
> The Official Toki Pona Dictionary is in the public domain.

tan ni la, mi pilin e ni: lipu https://gist.github.com/increpare/881d7f62a5f169014f09a6e9f110fe8a li lawa "CC BY-NC 4.0". jan Sonja li jo e ona.

**Comment by olpa** [comment]
Pona! https://github.com/olpa/gf-tokipona/commit/3098ebd20765f4eb4d20de38f73618e66074eae0

Tawa mi: mi pona lipu
```
tenpo suno nanpa tu la ona li kute e mu wawa .
jan NAME li kepeken ilo alasa , taso linja li pakala .
suno li loje , la tenpo pona li lon .
tenpo suno pini la jan NAME li pona e tomo , li telo e len .
mi kute e mije anu meli .
mi lon .
muku li pona!
sina pana e ike , la sina kamo jo e ike .
sewi li lon ala , li lon ale .
wile sona nanpa wan li ni : ale li pona anu ike ?
```

**Comment by olpa** [comment]
tenpo suno nanpa tu la ona li kute e mu wawa .
https://github.com/olpa/gf-tokipona/commit/51eba24a57ce44a7452038bd4a70a1a5cf40c538

**Comment by olpa** [comment]
Pona!
https://github.com/olpa/gf-tokipona/tree/master/external/pu_phrases
https://github.com/olpa/gf-tokipona/blob/6a92f958be85096d3c0273f9fe7121aff1441914/Makefile#L11
